export var USER_EXIST = 'USER_EXIST';
export const USER_FETCH = 'USER_FETCH';
export const USER_FETCH_UPDATE = 'USER_FETCH_UPDATE';
export const USER_FETCH_PASSWORD = 'USER_FETCH_PASSWORD';
export const USER_FETCH_PASSWORD_WRONG = 'USER_FETCH_PASSWORD_WRONG';
export const USER_RESERVATIONS_FETCH = 'USER_RESERVATIONS_FETCH';
